services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    env_file:
      - ytb-video-sharing-app-be/configs/config.dev.env
    ports:
      - '3307:3306'
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ytb

  backend:
    build:
      context: ./ytb-video-sharing-app-be
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - '3000:3000'
      - '3001:3001'
    networks:
      - ytb

  frontend:
    build:
      context: ./ytb-video-sharing-app-fe
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - backend
    environment:
      - VITE_WS_URL=ws://localhost:80/ws
      - VITE_API_URL=http://localhost:80/api/v1
      - VITE_API_KEY=AIzaSyCLQRWXvYfA59PDFKcBag87gGKxYiK7K5A
    ports:
      - '80:80'
    networks:
      - ytb
  # Zookeeper 1
  # zookeeper1:
  #   image: confluentinc/cp-zookeeper:latest
  #   container_name: zookeeper1
  #   restart: always
  #   environment:
  #     ZOOKEEPER_SERVER_ID: 1
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - ytb

  # # Kafka 1
  # kafka1:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: kafka1
  #   restart: always
  #   depends_on:
  #     - zookeeper1
  #   ports:
  #     - "29092:29092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  #     KAFKA_MIN_INSYNC_REPLICAS: 1
  #   networks:
  #     - ytb

  # # Kafka 2
  # kafka2:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: kafka2
  #   restart: always
  #   depends_on:
  #     - zookeeper1
  #   ports:
  #     - "29093:29093"
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29093
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093,PLAINTEXT_HOST://localhost:29093
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  #     KAFKA_MIN_INSYNC_REPLICAS: 1
  #   networks:
  #     - ytb

  # # Kafka 3
  # kafka3:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: kafka3
  #   restart: always
  #   depends_on:
  #     - zookeeper1
  #   ports:
  #     - "29094:29094"
  #   environment:
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,PLAINTEXT_HOST://0.0.0.0:29094
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094,PLAINTEXT_HOST://localhost:29094
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  #     KAFKA_MIN_INSYNC_REPLICAS: 1
  #   networks:
  #     - ytb

networks:
  ytb:
    driver: bridge

volumes:
  mysql_data:
